development:
  adapter: mysql
  database: aagnng8p_travels
  username: aagnng8p
  password: emdcwsntyuok

test:
  adapter: mysql
  database: aagnng8p_travels
  username: aagnng8p
  password: emdcwsntyuok

production:
  adapter: mysql
  database: aagnng8p_travels
  username: aagnng8p
  password: emdcwsntyuok


