development:
 api_key: b9b1ab2079e533379f446cbd34050c93
 secret_key: 796de8cb17e3fcc2acaf2bb7a95f8fea
 canvas_page_name: app
 callback_url: http://localhost:3000/
 pretty_errors: true
 set_asset_host_to_callback_url: false
